### ISSUE TITLE
i don't understand why use service

### ISSUE THREAD

**Issue by jianghejie** [sockeqwe/debugoverlay#2]
because i found that even if i exit the activity ,the overlay is still there .by the way ,variable  messageQueue  seems to be useless.

**Comment by jianghejie** [comment]
sorry  my mistake! if the ativity is destroyed,the overlay will be dismiss.
but still variable  messageQueue in the DebugOverlay class  seems to be useless.

**Comment by sockeqwe** [comment]
Hi, the idea is to have an overlay that is independent from Activities lifecycle.

Since starting and binding a service is not a blocking call, we have to wait until the service is bound before interacting with the `service`. The `messageQueue` is used as waiting queue for messages to log while the service is **not** bound yet. Once the service is bound all messages in the `messageQueue` will be dispatched and displayed in the overlay via `service`. If the service is already bound then the message to log will be dispatched directly to the service (without `messageQueue`)
